from pathlib import Path
p=Path('index.html');s=p.read_text()
old="APP_VERSION='2026.09.16-FINAL.10'"
assert s.count(old)==1
s=s.replace(old,"APP_VERSION='2026.09.16-FINAL.12'",1)
start=s.index('function renderTodayWithTasks(){');end=s.index('\n\nfunction initDays(){',start)
r="""function ensureVisitTaskConfirmModal(){var m=$id('visitTaskConfirmModal');if(m)return m;m=document.createElement('div');m.id='visitTaskConfirmModal';m.className='modal';m.innerHTML='<div class=\"sheet\"><div class=\"modalTop\"><div><div class=\"ey\">VISIT CHECK</div><div class=\"title\">タスクを個別に確認</div></div><button class=\"pill\" id=\"visitTaskConfirmClose\">閉じる</button></div><div class=\"notice\">この訪問で完了したタスクだけチェックしてください。未チェックは未完了のまま残ります。</div><div id=\"visitTaskConfirmList\"></div><div class=\"actions\"><button class=\"secondary\" id=\"visitTaskConfirmKeep\">未完了を残して訪問完了</button><button class=\"primary\" id=\"visitTaskConfirmApply\">チェックを反映して訪問完了</button></div></div>';document.body.appendChild(m);$id('visitTaskConfirmClose').onclick=function(){closeModal('visitTaskConfirmModal')};return m}
function continueVisitAfterTaskCheck(machine){selectedMachine=machine;if(machine.order){$id('orderVisitConfirmDetail').textContent=machine.order.type+(machine.order.sub?' ＞ '+machine.order.sub:'');closeModal('machineModal');openModal('orderVisitConfirm');return true}finishVisitCore();return true}
function openVisitTaskConfirm(machine){ensureVisitTaskConfirmModal();var box=$id('visitTaskConfirmList'),tasks=activeTasksForMachine(machine);box.innerHTML='';tasks.forEach(function(task){var p=taskProgress(task),row=document.createElement('label');row.style.cssText='display:flex;gap:10px;align-items:flex-start;padding:12px 2px;border-bottom:1px solid #eee';row.innerHTML='<input type=\"checkbox\" data-task-id=\"'+esc(task.id)+'\" style=\"width:20px;height:20px\"><span><b>'+esc(task.text||'タスク')+'</b><small style=\"display:block;color:#777;margin-top:3px\">全体進捗 '+p.done+' / '+p.total+'台</small></span>';box.appendChild(row)});function apply(checks){var chosen={};if(checks)box.querySelectorAll('input:checked').forEach(function(i){chosen[i.dataset.taskId]=1});tasks.forEach(function(t){if(!chosen[t.id])return;if(!machine.taskDone||typeof machine.taskDone!=='object')machine.taskDone={};machine.taskDone[t.id]={completedAt:Date.now()};completeParentTaskIfDone(t)});persist();closeModal('visitTaskConfirmModal');renderAll();continueVisitAfterTaskCheck(machine)}$id('visitTaskConfirmKeep').onclick=function(){apply(false)};$id('visitTaskConfirmApply').onclick=function(){apply(true)};openModal('visitTaskConfirmModal')}
function completeVisit(){if(!selectedMachine)return false;var tasks=activeTasksForMachine(selectedMachine);if(tasks.length){openVisitTaskConfirm(selectedMachine);return false}return continueVisitAfterTaskCheck(selectedMachine)}
function renderTodayWithTasks(){renderToday();var old=$id('todayTaskBlock');if(old)old.remove();var machines=sortedTodayMachines(targets(todayDay,false)),cards=Array.prototype.slice.call($id('todayList').querySelectorAll('.swipeCard'));cards.forEach(function(card,index){var machine=machines[index];if(!machine)return;var tasks=activeTasksForMachine(machine);if(!tasks.length)return;var wrap=document.createElement('div');wrap.className='todayMachineTasks';wrap.style.cssText='margin-top:9px;padding-top:8px;border-top:1px solid #eceef0';wrap.innerHTML='<div style=\"display:flex;justify-content:space-between;font-size:9px;font-weight:900\"><span style=\"color:#b42318\">TASK</span><span>'+tasks.length+'件</span></div>';tasks.slice(0,2).forEach(function(t){var pr=taskProgress(t),row=document.createElement('div');row.style.cssText='display:flex;justify-content:space-between;gap:8px;padding:3px 0;font-size:10px';row.innerHTML='<span style=\"overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-weight:800\">'+esc(t.text||'タスク')+'</span><strong style=\"font-size:9px;color:#666;white-space:nowrap\">'+pr.done+' / '+pr.total+'台</strong>';wrap.appendChild(row)});if(tasks.length>2){var more=document.createElement('div');more.style.cssText='font-size:9px;color:#777;font-weight:850';more.textContent='＋'+(tasks.length-2)+'件';wrap.appendChild(more)}card.appendChild(wrap)})}"""
s=s[:start]+r+s[end:]
p.write_text(s)
Path('version.json').write_text('{\n  "version": "2026.09.16-FINAL.12"\n}\n')
Path('ocr-config.js').write_text('(function(){"use strict";var e=window.VENDRIVE2OCRRelayConfig;if(!e||typeof e!=="object")window.VENDRIVE2OCRRelayConfig=Object.freeze({version:1,endpoint:"https://vendrive2-ocr-relay.vercel.app/api/ocr"});})();\n')