(function(global){
"use strict";
var DB_NAME="VENDRIVE2_ANALYTICS_DB",DB_VERSION=1,META_STORE="meta",SCHEMA_VERSION=1,ENGINE_VERSION="AN1";
var db=null,initializing=null,lastError=null;
function health(){return {dbName:DB_NAME,schemaVersion:SCHEMA_VERSION,engineVersion:ENGINE_VERSION,ready:!!db,error:lastError?String(lastError.message||lastError):null}}
function open(){if(db)return Promise.resolve(db);if(initializing)return initializing;if(!global.indexedDB){lastError=new Error("IndexedDB is unavailable");return Promise.reject(lastError)}var resolveOpen,rejectOpen,pending=new Promise(function(resolve,reject){resolveOpen=resolve;rejectOpen=reject});initializing=pending;function fail(error){lastError=error||new Error("Analytics database initialization failed");if(initializing===pending)initializing=null;rejectOpen(lastError)}var request;try{request=global.indexedDB.open(DB_NAME,DB_VERSION)}catch(error){fail(error);return pending}request.onupgradeneeded=function(){var database=request.result;if(!database.objectStoreNames.contains(META_STORE))database.createObjectStore(META_STORE,{keyPath:"key"})};request.onsuccess=function(){var database=request.result;db=database;database.onversionchange=function(){database.close();if(db===database)db=null;initializing=null};var tx;try{tx=database.transaction(META_STORE,"readwrite")}catch(error){if(db===database)db=null;fail(error);return}var store=tx.objectStore(META_STORE),metadata=store.get("engine");metadata.onsuccess=function(){var existing=metadata.result||{},now=new Date().toISOString();store.put({key:"engine",schemaVersion:SCHEMA_VERSION,engineVersion:ENGINE_VERSION,initializedAt:existing.initializedAt||now,updatedAt:now})};metadata.onerror=function(){try{tx.abort()}catch(error){}};tx.oncomplete=function(){if(db!==database){fail(new Error("Analytics database changed during initialization"));return}lastError=null;if(initializing===pending)initializing=null;resolveOpen(database)};tx.onerror=function(){if(db===database){database.close();db=null}fail(tx.error||new Error("Analytics meta initialization failed"))};tx.onabort=function(){if(db===database){database.close();db=null}fail(tx.error||new Error("Analytics meta initialization aborted"))}};request.onerror=function(){fail(request.error||new Error("Analytics database open failed"))};return pending}
function ready(){return open().then(function(){return health()})}
function exportSnapshot(){return open().then(function(database){return new Promise(function(resolve,reject){var tx=database.transaction(META_STORE,"readonly"),request=tx.objectStore(META_STORE).getAll();request.onsuccess=function(){resolve({kind:"VENDRIVE2_ANALYTICS_BACKUP",formatVersion:1,schemaVersion:SCHEMA_VERSION,engineVersion:ENGINE_VERSION,createdAt:new Date().toISOString(),stores:{meta:request.result||[]}})};request.onerror=function(){reject(request.error||new Error("Analytics export failed"))}})})}
function close(){if(db){db.close();db=null}initializing=null}
global.VENDRIVE2Analytics={ready:ready,getHealth:health,exportSnapshot:exportSnapshot,close:close};
ready().catch(function(error){lastError=error;if(global.console&&global.console.warn)global.console.warn("VENDRIVE2 analytics sidecar initialization failed",error)});
})(window);