const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
function env(){const mem=new Map();const localStorage={getItem:k=>mem.has(k)?mem.get(k):null,setItem:(k,v)=>mem.set(k,String(v)),removeItem:k=>mem.delete(k)};const sandbox={console,JSON,Date,Math,isFinite,localStorage,setInterval:()=>0,clearInterval:()=>{}};sandbox.window=sandbox;sandbox.globalThis=sandbox;vm.createContext(sandbox);vm.runInContext(fs.readFileSync('an15a-forecast-scoring.js','utf8'),sandbox);vm.runInContext(fs.readFileSync('an15-lifecycle-integration.js','utf8'),sandbox);return sandbox}
function forecast(over={}){return Object.assign({forecastId:'f1',seriesKey:'s1',asOf:'2026-09-01T00:00:00.000Z',machineId:'m1',productId:'p1',forecastKnown:true,forecastUnitsPerDay:4,lowerBound:false},over)}
function report(over={}){return Object.assign({id:'r1',type:'sales',status:'confirmed',payloadVersion:1,machineId:'m1',makerKey:'mk',occurredAt:'2026-09-02T00:00:00.000Z',current:{previousClearAt:'2026-09-01T00:00:00.000Z',products:[{productCode:'c1',salesQty:5}],soldOuts:[]}},over)}
test('snapshot aggregates machine-product series and is idempotent',()=>{const s=env(),api=s.VENDRIVE2AN15Lifecycle,ledger=s.VENDRIVE2ForecastScoring;const rows=[forecast(),forecast({forecastId:'f2',seriesKey:'s2',forecastUnitsPerDay:3})];assert.equal(api.snapshotForecasts(rows).snapshots,1);assert.equal(api.snapshotForecasts(rows).snapshots,1);const all=ledger.list();assert.equal(all.length,1);assert.equal(all[0].predictedUnits,7);assert.equal(all[0].targetAt,'2026-09-02T00:00:00.000Z')});
test('unknown and lower-bound forecasts never become exact snapshots',()=>{const s=env(),api=s.VENDRIVE2AN15Lifecycle,ledger=s.VENDRIVE2ForecastScoring;api.snapshotForecasts([forecast({lowerBound:true})]);api.snapshotForecasts([forecast({forecastKnown:false,forecastUnitsPerDay:null})]);assert.equal(ledger.list().length,0)});
test('only exact next 24h confirmed interval scores',()=>{const s=env(),api=s.VENDRIVE2AN15Lifecycle,ledger=s.VENDRIVE2ForecastScoring;api.snapshotForecasts([forecast({productId:'["mk","c1"]'})]);let r=report();assert.equal(api.scoreConfirmedReport(r).scored,1);let row=ledger.list()[0];assert.equal(row.score.eligibleExact,true);assert.equal(row.outcome.observedUnits,5);ledger._clearForTests();api.snapshotForecasts([forecast({productId:'["mk","c1"]'})]);r=report({occurredAt:'2026-09-02T01:00:00.000Z'});assert.equal(api.scoreConfirmedReport(r).scored,0);assert.equal(ledger.list()[0].score,null)});
test('sold-out outcome is scored but excluded from exact learning',()=>{const s=env(),api=s.VENDRIVE2AN15Lifecycle,ledger=s.VENDRIVE2ForecastScoring;api.snapshotForecasts([forecast({productId:'["mk","c1"]'})]);const r=report();r.current.soldOuts=[{productCode:'c1',column:1,temperature:'COLD'}];api.scoreConfirmedReport(r);const row=ledger.list()[0];assert.equal(row.outcome.censored,true);assert.equal(row.score.eligibleExact,false);assert.equal(ledger.metrics().exactSampleSize,0)});
test('unconfirmed/non-sales reports cannot score',()=>{const s=env(),api=s.VENDRIVE2AN15Lifecycle,ledger=s.VENDRIVE2ForecastScoring;api.snapshotForecasts([forecast({productId:'["mk","c1"]'})]);assert.equal(api.scoreConfirmedReport(report({status:'draft'})).scored,0);assert.equal(ledger.list()[0].score,null)});
