const ALLOWED_ORIGINS=new Set(["https://tenta0604.github.io","http://localhost:8000","http://127.0.0.1:8000"]);
const DEFAULT_MODEL="gemini-3.6-flash";
const MAX_BODY_BYTES=64*1024;
function cors(origin){const h={"Vary":"Origin","Cache-Control":"no-store","Content-Type":"application/json; charset=utf-8"};if(ALLOWED_ORIGINS.has(origin))h["Access-Control-Allow-Origin"]=origin;h["Access-Control-Allow-Methods"]="POST, OPTIONS";h["Access-Control-Allow-Headers"]="Content-Type, Accept";return h}
function json(status,body,origin){return new Response(JSON.stringify(body),{status,headers:cors(origin)})}
function s(v,max=240){return typeof v==="string"&&v.trim()?v.trim().slice(0,max):null}
function finite(v){return typeof v==="number"&&Number.isFinite(v)}
function strings(v,maxItems=8,maxLen=240){return Array.isArray(v)?v.filter(x=>typeof x==="string"&&x.trim()).slice(0,maxItems).map(x=>x.trim().slice(0,maxLen)):[]}
function cleanGrounding(raw){if(!raw||typeof raw!=="object")return null;const facts=Array.isArray(raw.facts)?raw.facts.slice(0,24).map(f=>f&&typeof f==="object"&&s(f.label,100)?{label:s(f.label,100),value:(typeof f.value==="string"?s(f.value,160):finite(f.value)||typeof f.value==="boolean"?f.value:null),unit:s(f.unit,40),sourceRefs:strings(f.sourceRefs,8,160)}:null).filter(Boolean):[];let proposal=null;if(raw.proposal&&typeof raw.proposal==="object")proposal={action:s(raw.proposal.action,240),rank:finite(raw.proposal.rank)?raw.proposal.rank:null,confidence:finite(raw.proposal.confidence)?raw.proposal.confidence:null,requiresUserConfirmation:true,autoApply:false,sourceRefs:strings(raw.proposal.sourceRefs,8,160)};return {kind:s(raw.kind,80)||"analysis",title:s(raw.title,160),facts,proposal,unknowns:strings(raw.unknowns,12,200),caveats:strings(raw.caveats,12,240)}}
function extractText(data){const p=data&&data.candidates&&data.candidates[0]&&data.candidates[0].content&&data.candidates[0].content.parts;if(Array.isArray(p))for(const x of p)if(x&&typeof x.text==="string")return x.text;throw new Error("missing_text")}
const schema={type:"object",additionalProperties:false,properties:{headline:{type:"string",maxLength:160},summary:{type:"string",maxLength:800},why:{type:"array",maxItems:6,items:{type:"string",maxLength:240}},uncertainty:{type:"array",maxItems:6,items:{type:"string",maxLength:240}},review:{type:"array",maxItems:6,items:{type:"string",maxLength:240}}},required:["headline","summary","why","uncertainty","review"]};
async function handle(request){const origin=request.headers.get("origin")||"";if(request.method==="OPTIONS"){if(!ALLOWED_ORIGINS.has(origin))return json(403,{error:"Origin is not allowed"},origin);return new Response(null,{status:204,headers:cors(origin)})}if(request.method!=="POST")return json(405,{error:"Method not allowed"},origin);if(!ALLOWED_ORIGINS.has(origin))return json(403,{error:"Origin is not allowed"},origin);const len=Number(request.headers.get("content-length")||0);if(len>MAX_BODY_BYTES)return json(413,{error:"Explanation payload is too large"},origin);let body;try{body=await request.json()}catch(e){return json(400,{error:"Invalid JSON"},origin)}const grounding=cleanGrounding(body&&body.grounding);if(!grounding)return json(400,{error:"Grounding is required"},origin);const apiKey=process.env.GEMINI_API_KEY||"";if(!apiKey)return json(503,{error:"Explanation provider authentication is unavailable"},origin);const prompt=["You explain VENDRIVE2 vending analytics to a human operator in concise Japanese.","GROUNDING is the complete and only source of truth.","Never recalculate, modify, rank, optimize, or replace any numeric forecast, score, quantity, confidence, proposal, or recommendation.","Never invent facts, weather, calendar events, costs, inventory, product attributes, causal explanations, or source references.","Correlation is not causation. If causality is not explicitly established in GROUNDING, do not claim it.","Unknowns must remain unknown. Mention material uncertainty.","Explain why the supplied result exists and what the human should review. Do not issue commands that auto-apply changes.","GROUNDING:",JSON.stringify(grounding)].join("\n");const model=(process.env.EXPLAIN_GEMINI_MODEL||process.env.OCR_GEMINI_MODEL||DEFAULT_MODEL).trim()||DEFAULT_MODEL;let upstream;try{upstream=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:"POST",headers:{"x-goog-api-key":apiKey,"Content-Type":"application/json"},body:JSON.stringify({contents:[{role:"user",parts:[{text:prompt}]}],generationConfig:{responseMimeType:"application/json",responseJsonSchema:schema,temperature:0.2}})})}catch(e){return json(502,{error:"Explanation provider unavailable"},origin)}let data;try{data=await upstream.json()}catch(e){return json(502,{error:"Invalid provider response"},origin)}if(!upstream.ok)return json(upstream.status===429?429:502,{error:"Explanation provider rejected request"},origin);let parsed;try{parsed=JSON.parse(extractText(data))}catch(e){return json(502,{error:"Explanation provider returned invalid structured data"},origin)}return json(200,{ok:true,provider:"google-gemini-api",model,explanation:{headline:s(parsed.headline,160)||grounding.title||"分析結果",summary:s(parsed.summary,800)||"",why:strings(parsed.why,6,240),uncertainty:strings(parsed.uncertainty,6,240),review:strings(parsed.review,6,240)},grounding},origin)}
export default handle;
